// <auto-generated />
using HybridCacheDemo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HybridCacheDemo.Migrations
{
    [DbContext(typeof(EfContext))]
    [Migration("20250729224844_initialMigration")]
    partial class initialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HybridCacheDemo.Data.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "J.R.R. Tolkien",
                            Genre = "Fantasy",
                            Title = "The Fellowship of the Ring",
                            Year = 1954
                        },
                        new
                        {
                            Id = 2,
                            Author = "J.R.R. Tolkien",
                            Genre = "Fantasy",
                            Title = "The Two Towers",
                            Year = 1954
                        },
                        new
                        {
                            Id = 3,
                            Author = "J.R.R. Tolkien",
                            Genre = "Fantasy",
                            Title = "The Return of the King",
                            Year = 1955
                        },
                        new
                        {
                            Id = 4,
                            Author = "Frank Herbert",
                            Genre = "Science Fiction",
                            Title = "Dune",
                            Year = 1965
                        },
                        new
                        {
                            Id = 5,
                            Author = "Orson Scott Card",
                            Genre = "Science Fiction",
                            Title = "Ender's Game",
                            Year = 1985
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
